"""Generate 5-page onboarding brief PDF for Velora demo."""
import os
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.colors import HexColor


def generate_onboarding_pdf():
    """Generate a 5-page onboarding brief for Velora."""
    os.makedirs("static", exist_ok=True)
    doc = SimpleDocTemplate(
        "static/onboarding_brief.pdf",
        pagesize=letter,
        topMargin=1 * inch,
        bottomMargin=1 * inch,
        leftMargin=1 * inch,
        rightMargin=1 * inch,
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=24,
        textColor=HexColor("#5B21B6"),
        spaceAfter=30,
    )
    story = []

    # Page 1
    story.append(Paragraph("Welcome to Velora", title_style))
    story.append(Paragraph("Your AI-Powered Onboarding Guide", styles["Heading2"]))
    story.append(Spacer(1, 0.5 * inch))
    story.append(
        Paragraph(
            "This brief was automatically generated by OnboardAI based on your company's "
            "Notion docs, GitHub repos, and Slack conversations. It contains everything "
            "you need to know about Velora, our product, market, and team.",
            styles["BodyText"],
        )
    )
    story.append(PageBreak())

    # Page 2
    story.append(Paragraph("Company Overview", title_style))
    story.append(
        Paragraph(
            "<b>Mission:</b> Reduce e-commerce support tickets by 80% using AI<br/>"
            "<b>Product:</b> AI customer support platform for Shopify/WooCommerce<br/>"
            "<b>Founded:</b> 2023<br/><b>Team Size:</b> 15 people<br/>"
            "<b>Funding:</b> $2.5M seed round (Bessemer Venture Partners)<br/>"
            "<b>Runway:</b> 24 months<br/>",
            styles["BodyText"],
        )
    )
    story.append(PageBreak())

    # Page 3
    story.append(Paragraph("Product & Technology", title_style))
    story.append(
        Paragraph(
            "<b>Tech Stack:</b><br/>"
            "• Backend: Python/FastAPI, PostgreSQL, Redis<br/>"
            "• Frontend: React/TypeScript<br/>"
            "• AI: GPT-4, Pinecone vector search<br/>"
            "• Infrastructure: AWS, Docker, GitHub Actions<br/><br/>"
            "<b>Key Features:</b><br/>"
            "• 5-minute setup for merchants<br/>"
            "• Auto-learns from past tickets<br/>"
            "• Native Shopify/WooCommerce integration<br/>"
            "• Multi-language support (10+ languages)<br/>",
            styles["BodyText"],
        )
    )
    story.append(PageBreak())

    # Page 4
    story.append(Paragraph("Market & Competition", title_style))
    story.append(
        Paragraph(
            "<b>Target Market:</b> Mid-size e-commerce ($10M-$100M ARR)<br/><br/>"
            "<b>Competitors:</b><br/>"
            "• Intercom: Enterprise focus, expensive ($50k+ ACV)<br/>"
            "• Zendesk: Legacy platform, slow innovation<br/>"
            "• Gorgias: Direct competitor, but 3x our price<br/><br/>"
            "<b>Our Advantages:</b><br/>"
            "• 70% cheaper than alternatives<br/>"
            "• 10x faster setup (5 mins vs hours)<br/>"
            "• Better AI responses (GPT-4 powered)<br/>",
            styles["BodyText"],
        )
    )
    story.append(PageBreak())

    # Page 5
    story.append(Paragraph("Getting Started", title_style))
    story.append(
        Paragraph(
            "<b>Your First Week:</b><br/>"
            "• Day 1: Meet the team, access all tools<br/>"
            "• Day 2-3: Product deep dive and demos<br/>"
            "• Day 4-5: Shadow customer calls<br/>"
            "• Week 2: Start your first project<br/><br/>"
            "<b>Key Resources:</b><br/>"
            "• Notion: wiki.velora.ai<br/>"
            "• GitHub: github.com/velora-ai<br/>"
            "• Slack: velora.slack.com<br/><br/>"
            "<i>Generated by OnboardAI - Powered by Composio, You.com, and Render</i>",
            styles["BodyText"],
        )
    )
    doc.build(story)
    print("✅ PDF onboarding brief generated at static/onboarding_brief.pdf")


if __name__ == "__main__":
    generate_onboarding_pdf()
